# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cesrra
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: node-express-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: practice-serverless-node-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL, "fallback value"}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"
plugins:
  - serverless-offline
  - serverless-dotenv-plugin